language: elixir

elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.1
otp_release:
  - 19.3
  - 20.3
  - 21.0

matrix:
  exclude:
  - elixir: 1.4.5
    otp_release: 21.0
  - elixir: 1.5.3
    otp_release: 21.0
  - elixir: 1.7.1
    otp_release: 19.3

dist: trusty
install:
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
script:
  - rebar3 compile